= About Me
:browser-title: about
:page-path: /about/
:description: About Arthur Taft

== Personal

I was born at a very young age in Salt Lake City, UT and spent the first 10 years of my life living in the Liberty Wells neighborhood. Subsequently my family moved to the west side of Salt Lake. I am a student at Southern Utah University studying: Cybersecurity, Music, and German.

== Professional

I started my work history at Lagoon Amusement Park in Farmington, UT where I held 3 positions: Ride Operator (2022), Ride Supervisor (2022), Ride Coordinator (2023). This is where a majority of my customer service, as well as leadership experience comes from. Upon starting school I worked for the SUU IT Help Desk (2024), where I stayed for a little less than a year. After returning to Salt Lake to save money to continue school I began work for The Church of Jesus Christ of Latter-day Saints at Beehive Clothing as a Packing Operator (2026). In May 2026 I returned to Cedar City and began working at the SUU IT Help Desk again. In June I received a promotion to IT Help Desk Specialist, and also became the Cybersecurity Club President.

== Hobbies

In my spare time I like to work on developing my homelab and learning about self-hosting different services. I enjoy learning about operating systems, with an emphasis on Gentoo Linux, FreeBSD, and other Linux's. In addition to my technology interests, I also enjoy playing the trombone, and have been a member of the SUU Marching Band, Basketball Band, and Symphonic Band.
